# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:6.9.4

pipelines:
  custom:
    sonar:
      - step:
          name: Push 1
          script:
            - if [[ $BITBUCKET_BRANCH != master ]]; then echo "Wrong branch. Expected 'Preview'"; exit 1; fi
            - echo 11

    sonar1:
      - step:
          name: Push 2
          script:
            - if [[ $BITBUCKET_BRANCH != Preview ]]; then echo "Wrong branch. Expected 'Preview'"; exit 1; fi
            - echo OK
