# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:6.9.4

pipelines:
  custom: # Pipelines that can only be triggered manually
    sonar:
      - step:
          name: Push
          script:
            - if [[ "$BITBUCKET_BRANCH" -eq "Preview" ]]; then echo "File does not exist PR"; fi
            - if [[ "$BITBUCKET_BRANCH" -eq "Sandbox" ]]; then echo "File does not exist SB"; fi
            - if [[ "$BITBUCKET_BRANCH" -eq "master" ]]; then echo "File does not exist ms"; fi
